---
title: "lassoCox"
author: "Haiyu GOng"
date: "`r Sys.Date()`"
output: html_document
---

# Load Data

```{r}

library(survival)
library(survminer)
library("readxl")
library(ggplot2)
path <- "C:\\Users\\GongHaiyu\\OneDrive\\病理\\tableData\\resultTable_0510f1v3.xlsx"
data1 <- read_excel(path, sheet = "FUSCC")
data2 <- read_excel(path, sheet = "Training")
data3 <- read_excel(path, sheet = "InternalValid")
data4 <- read_excel(path, sheet = "External2")

indices <- c( 'MH_new', 'auto_ki67', 'manual_ki67', 
       'ki67_max', 'ki67_min', 'ki67_mean', 'ki67_std',
       'ki67_cv', 'ki67_range', 'ki67_median', 'ki67_SquMean', 'ki67_Skewness',
       'ki67_kurt', 'ki67_IQR', 'ki67_QCD', 
       'entropy_max', 'entropy_min', 'entropy_mean', 'entropy_std', 
       'entropy_cv', 'entropy_range', 'entropy_median', 'entropy_SquMean', 'entropy_Skewness', 
       'entropy_kurt', 'entropy_IQR', 'entropy_QCD'
        ,'pct_HH', 'pct_sig', 'pct_Gsig'
       #, 'risk_score', 'risk_score_gd', 'risk_score_lasso', 'risk_score_ridge', 'risk_score_mlp'
       )
#indices <- c( 'MH_new', 'entropy_Skewness')
```

```{r}
#ids_to_remove <- c(18, 87, 25, 2, 83, 34,114, 187, 196,197)  # 用实际的 ID 值替换这些示例值
#data1 <- data1[!data1$id %in% ids_to_remove, ]
#data2 <- data2[!data2$id %in% ids_to_remove, ]
#data3 <- data3[!data3$id %in% ids_to_remove, ]
#data4 <- data4[!data4$id %in% ids_to_remove, ]

#hospital_to_remove <- c('ZZU', 'ZS', 'CZ', 'HS')
#data4 <- data4[data4$hospital %in% hospital_to_remove, ]
```


```{r}
# 假设你有一个名为 status 的列，其中包含了 0-1 编码的状态
#data1$OS_status <- ifelse(data1$OS_status == 0, 1, 2)

# 假设你的数据框名为 data1，时间列名为 time
data1 <- data1[data1$OS_months > 0, ]
data2 <- data2[data2$OS_months > 0, ]
data3 <- data3[data3$OS_months > 0, ]
data4 <- data4[data4$OS_months > 0, ]

# 创建输入特征 x 和生存时间与事件 y
x <- as.matrix(data1[, indices])  # 忽略第一列（id）和第二列（生存时间）
y <- Surv(data1$OS_months, data1$OS_status)
x_train <- as.matrix(data2[, indices])  # 忽略第一列（id）和第二列（生存时间）
y_train <- Surv(data2$OS_months, data2$OS_status)
x_internal_valid <- as.matrix(data3[, indices])  # 忽略第一列（id）和第二列（生存时间）
y_internal_valid <- Surv(data3$OS_months, data3$OS_status)
x_external_valid <- as.matrix(data4[, indices])  # 忽略第一列（id）和第二列（生存时间）
y_external_valid <- Surv(data4$OS_months, data4$OS_status)
```

```{r}
# 加载所需的包
#install.packages("glmnet")
library(glmnet)
#install.packages("survival")
library(survival)

# 使用内置的 lung 数据集
#data(lung)

# 删除包含缺失值的行
#lung_clean <- lung[complete.cases(lung), ]

# 使用 Lasso Cox 回归拟合模型
lasso_model <- cv.glmnet(x_train, y_train, family = "cox", alpha = 1)

# 打印最优模型的结果
print(lasso_model)

# 画出交叉验证的结果
plot(lasso_model)

# 选择最佳的 lambda 值
best_lambda <- lasso_model$lambda.min
best_lambda <- 0.05446783
# 根据最佳 lambda 值重新拟合模型
lasso_model_final <- glmnet(x_train, y_train, family = "cox", alpha = 1, lambda = best_lambda)

# 打印最终模型的系数
coef(lasso_model_final)



# 对预测结果进行评估

```


```{r}
# 定义函数计算C-index
c_index <- function(predicted, observed_time, observed_event) {
  n <- length(predicted)
  concordant <- 0
  discordant <- 0
  ties <- 0
  
  for (i in 1:(n-1)) {
    for (j in (i+1):n) {
      if (observed_time[i] != observed_time[j]) {
        if ((predicted[i] < predicted[j]) && (observed_time[i] < observed_time[j])) {
          concordant <- concordant + 1
        } else if ((predicted[i] > predicted[j]) && (observed_time[i] > observed_time[j])) {
          concordant <- concordant + 1
        } else if (predicted[i] == predicted[j]) {
          ties <- ties + 1
        } else {
          discordant <- discordant + 1
        }
      }
    }
  }
  
  c_index <- (concordant + 0.5 * ties) / (concordant + discordant + ties)
  return(c_index)
}

# 预测
pred_train <- predict(lasso_model_final, s = best_lambda, newx = x_train)
pred_internal_valid <- predict(lasso_model_final, s = best_lambda, newx = x_internal_valid)
pred_external_valid <- predict(lasso_model_final, s = best_lambda, newx = x_external_valid)
data2$lasso_cox <- as.vector(pred_train)
data3$lasso_cox <- as.vector(pred_internal_valid)
data4$lasso_cox <- as.vector(pred_external_valid)

# 计算C-index
c_index_train <- c_index(pred_train, data2$OS_status, data2$OS_status)
print(paste("Train Concordance Index (C-index):", c_index_train))
c_index_internal_valid <- c_index(pred_internal_valid, data3$OS_status, data3$OS_status)
print(paste("Internal Valid Concordance Index (C-index):", c_index_internal_valid))
c_index_external_valid <- c_index(pred_external_valid, data4$OS_status, data4$OS_status)
print(paste("External Valid Concordance Index (C-index):", c_index_external_valid))
```

### training
```{r}
indices2 <- c('MH_new', 'auto_ki67', 'manual_ki67', 'ki67_std',
       'entropy_SquMean', 'entropy_Skewness', 'entropy_QCD', 'lasso_cox')
res.cut <- surv_cutpoint(data2, 
                         time = "OS_months", 
                         event = "OS_status",
                         variables = indices2
                        )

summary(res.cut)

res.cat <- surv_categorize(res.cut)

plot(res.cut, "MH_new")
plot(res.cut, "auto_ki67")
plot(res.cut, "manual_ki67")

plot(res.cut, "ki67_std")

plot(res.cut, "entropy_SquMean")
plot(res.cut, "entropy_Skewness")
plot(res.cut, "entropy_QCD")
```

```{r}
res.cat <- surv_categorize(res.cut)

fit <- survfit(Surv(OS_months, OS_status) ~ MH_new, data = res.cat)#拟合生存分析
#绘制生存曲线并显示P值
ggsurvplot(fit,
           data = res.cat,
           risk.table = TRUE,
           pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ auto_ki67, data = res.cat)
ggsurvplot(fit, data = res.cat, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ manual_ki67, data = res.cat)
ggsurvplot(fit, data = res.cat, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ ki67_std, data = res.cat)
ggsurvplot(fit, data = res.cat, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ entropy_SquMean, data = res.cat)
ggsurvplot(fit, data = res.cat, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ entropy_Skewness, data = res.cat)
fit <- survfit(Surv(OS_months, OS_status) ~ entropy_QCD, data = res.cat)
ggsurvplot(fit, data = res.cat, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ lasso_cox, data = res.cat)
ggsurvplot(fit, data = res.cat, risk.table = TRUE, pval = T)
```

### Internal Validaion

```{r}


data3$MH_new <- cut(data3$MH_new,
                             breaks = c(-Inf, res.cut[["MH_new"]]["estimate"], Inf),
                             labels = c("low", "high"),
                             include.lowest = TRUE)


data3$auto_ki67 <- cut(data3$auto_ki67, breaks = c(-Inf, res.cut[["auto_ki67"]]["estimate"], Inf), labels = c("low", "high"), include.lowest = TRUE)
data3$manual_ki67 <- cut(data3$manual_ki67, breaks = c(-Inf, res.cut[["manual_ki67"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)

data3$ki67_std <- cut(data3$ki67_std, breaks = c(-Inf, res.cut[["ki67_std"]]["estimate"], Inf), labels = c("low", "high"), include.lowest = TRUE)

data3$entropy_SquMean <- cut(data3$entropy_SquMean, breaks = c(-Inf, res.cut[["entropy_SquMean"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)
data3$entropy_Skewness <- cut(data3$entropy_Skewness, breaks = c(-Inf, res.cut[["entropy_Skewness"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)
data3$entropy_QCD <- cut(data3$entropy_QCD, breaks = c(-Inf, res.cut[["entropy_QCD"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)

data3$lasso_cox <- cut(data3$lasso_cox, breaks = c(-Inf, res.cut[["lasso_cox"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)
```

```{r}
fit <- survfit(Surv(OS_months, OS_status) ~ MH_new, data = data3)#拟合生存分析
#绘制生存曲线并显示P值
ggsurvplot(fit,
           data = data3,
           risk.table = TRUE,
           pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ auto_ki67, data = data3)
ggsurvplot(fit, data = data3, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ manual_ki67, data = data3)
ggsurvplot(fit, data = data3, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ ki67_std, data = data3)
ggsurvplot(fit, data = data3, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ entropy_SquMean, data = data3)
ggsurvplot(fit, data = data3, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ entropy_Skewness, data = data3)
ggsurvplot(fit, data = data3, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ entropy_QCD, data = data3)
ggsurvplot(fit, data = data3, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ lasso_cox, data = data3)
ggsurvplot(fit, data = data3, risk.table = TRUE, pval = T)

```

### External Validaion

```{r}


data4$MH_new <- cut(data4$MH_new,
                             breaks = c(-Inf, res.cut[["MH_new"]]["estimate"], Inf),
                             labels = c("low", "high"),
                             include.lowest = TRUE)


data4$auto_ki67 <- cut(data4$auto_ki67, breaks = c(-Inf, res.cut[["auto_ki67"]]["estimate"], Inf), labels = c("low", "high"), include.lowest = TRUE)
data4$manual_ki67 <- cut(data4$manual_ki67, breaks = c(-Inf, res.cut[["manual_ki67"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)

data4$ki67_std <- cut(data4$ki67_std, breaks = c(-Inf, res.cut[["ki67_std"]]["estimate"], Inf), labels = c("low", "high"), include.lowest = TRUE)

data4$entropy_SquMean <- cut(data4$entropy_SquMean, breaks = c(-Inf, res.cut[["entropy_SquMean"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)
data4$entropy_Skewness <- cut(data4$entropy_Skewness, breaks = c(-Inf, res.cut[["entropy_Skewness"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)
data4$entropy_QCD <- cut(data4$entropy_QCD, breaks = c(-Inf, res.cut[["entropy_QCD"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)

data4$lasso_cox <- cut(data4$lasso_cox, breaks = c(-Inf, res.cut[["lasso_cox"]]["estimate"]	, Inf), labels = c("low", "high"), include.lowest = TRUE)

```

```{r}
fit <- survfit(Surv(OS_months, OS_status) ~ MH_new, data = data4)#拟合生存分析
#绘制生存曲线并显示P值
ggsurvplot(fit,
           data = data4,
           risk.table = TRUE,
           pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ auto_ki67, data = data4)
ggsurvplot(fit, data = data4, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ manual_ki67, data = data4)
ggsurvplot(fit, data = data4, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ ki67_std, data = data4)
ggsurvplot(fit, data = data4, risk.table = TRUE, pval = T)


fit <- survfit(Surv(OS_months, OS_status) ~ entropy_SquMean, data = data4)
ggsurvplot(fit, data = data4, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ entropy_Skewness, data = data4)
ggsurvplot(fit, data = data4, risk.table = TRUE, pval = T)
fit <- survfit(Surv(OS_months, OS_status) ~ entropy_QCD, data = data4)
ggsurvplot(fit, data = data4, risk.table = TRUE, pval = T)

fit <- survfit(Surv(OS_months, OS_status) ~ lasso_cox, data = data4)
ggsurvplot(fit, data = data4, risk.table = TRUE, pval = T)
```

